#! /bin/sh

# pubsubplus-go-client
#
# Copyright 2023-2025 Solace Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# generates a command equivalent to:
# rm -rf /output/action/api /output/action/docs /output/action/.swagger-codegen* /output/action/*.go /output/action/*.sh /output/action/*.md /output/action/*.yml /output/action/.gitignore /output/monitor/api /output/monitor/docs /output/monitor/.swagger-codegen* /output/monitor/*.go /output/monitor/*.sh /output/monitor/*.md /output/monitor/*.yml /output/monitor/.gitignore /output/config/api /output/config/docs /output/action/.swagger-codegen* /output/config/*.go /output/config/*.sh /output/config/*.md /output/config/*.yml /output/config/.gitignore
# This command can be run from the host or from the codegen container
# The files to delete can change over time

BASEDIR=$(cd $(dirname $0) && pwd)

function cleanup_files() {
    echo "from `pwd` cleanup $*"
    rm -rf $*
}
function cleanup() {
    echo "args $*"
    echo "script dir $BASEDIR"
    echo "Current dir `pwd`"

    local gen_root_dir=${BASEDIR}
    local gen_dirs=" action config monitor "
    local sub_gen_dirs=".swagger-codegen* docs api"
    local gen_files=" *.go *.sh *.md *.yml .gitignore .*.yml"

    for topdir in $gen_dirs ; do
        local cur_dir=$gen_root_dir/$topdir
        if [[ -e $cur_dir ]]; then
            (cd $cur_dir; cleanup_files $sub_gen_dirs ) && (cd $cur_dir; cleanup_files $gen_files )
        fi
    done

}
cleanup $*
